<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="20428" started-at="2018-05-13T07:44:02Z" finished-at="2018-05-13T07:44:22Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="20428" started-at="2018-05-13T07:44:02Z" finished-at="2018-05-13T07:44:22Z">
      <class name="testscripts.TC001_TestLogin">
        <test-method status="PASS" signature="OpenBrowser()[pri:0, instance:testscripts.TC001_TestLogin@1a968a59]" name="OpenBrowser" is-config="true" duration-ms="14379" started-at="2018-05-13T07:44:02Z" finished-at="2018-05-13T07:44:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenBrowser -->
        <test-method status="FAIL" signature="TestLogin()[pri:0, instance:testscripts.TC001_TestLogin@1a968a59]" name="TestLogin" duration-ms="5781" started-at="2018-05-13T07:44:16Z" finished-at="2018-05-13T07:44:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My ACCOUNT] but found [MY ACCOUNT]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My ACCOUNT] but found [MY ACCOUNT]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at pagelibrary.SignIn.VerifyLogin(SignIn.java:69)
at testscripts.TC001_TestLogin.TestLogin(TC001_TestLogin.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestLogin -->
        <test-method status="PASS" signature="QuitBrowser()[pri:0, instance:testscripts.TC001_TestLogin@1a968a59]" name="QuitBrowser" is-config="true" duration-ms="141" started-at="2018-05-13T07:44:22Z" finished-at="2018-05-13T07:44:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- QuitBrowser -->
      </class> <!-- testscripts.TC001_TestLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
